### ISSUE TITLE
GCODE Scaling issue with Inkscape 0.91

### ISSUE THREAD

**Issue by virdi** [KnoxMakers/KM-Laser#11]
A bugging issue: 
When I use the latest version of Inkscape and KM extension (on Mac or Windows), the resulting GCODE is 'scaled' down to roughly 25% of the original.

Reproduce/Example: The relevant portions of GCODE corresponding to a rectangle 200mm x 100mm, placed at 10,10 on the KM template:
M62 P0 (BURN ON MOVE)
G01 X59.235431 Y31.013208 Z-0.000001 F500.000000
G01 X59.235431 Y2.853455 Z-0.000001
G01 X2.853457 Y2.853455 Z-0.000001
G01 X2.853457 Y31.013208 Z-0.000001
G00 Z0.000001 (LASER OFF)

This GCODE doesn't really look like a 200mm x 100mm rectangle. (Find attached the SVG and GCODE files)

**Comment by jondale** [comment]
This issue has been fixed for a while.

For versions prior to version 0.92 use the branch pre_0.92
For versions 0.92 and above use the master branch.
