### ISSUE TITLE
Generate Hatchfill not working

### ISSUE THREAD

**Issue by HunterG6700** [KnoxMakers/KM-Laser#14]
I do not know if its me or what, but I couldn't get the Generate Hatchfill to work on Inkscape version 1

**Comment by bucket832** [comment]
Same, I don't think it is updated for this version of inkscape.

**Comment by jondale** [comment]
KM-Laser has not yet been updated for Inkscape 1.0 yet.
I will look at it.

**Comment by jondale** [comment]
Thank you for the report.  The repo has not been updated for 1.0+
