### ISSUE TITLE
Wrong location for Mac

### ISSUE THREAD

**Issue by vt102** [KnoxMakers/KM-Laser#15]
MacOS 15.5.4 (Catalina)
Inkscape 1.0 (4035a4f, 2020-05-01)

Correct location for user extensions were incorrect for me; correct location was:
```
~/Library/Application\ Support/org.inkscape.Inkscape/config/inkscape/extensions 
```

**Comment by jondale** [comment]
Thanks for the PR.  It's merged and that closes this issue.
