### ISSUE TITLE
Cutting the same path multiple times

### ISSUE THREAD

**Issue by laz1861** [KnoxMakers/KM-Laser#6]
I've got a file that I'm trying to cut out.  I'm having problems where certain parts of it are being cut two and even three times.  Based on how this is behaving on my project, I believe this bug is related to layers.

I've done a lot of work on this file with the tabbed box maker, which seems to make a bunch of layers for me. If I'm cutting out things from different layers, it seems to cut everything in the first layer, then everything in the first and second layer, then everything in the first, second, and third layer, etc.  

We maybe have sort of looping issue that's not excluding things correctly?  I'm not sure.  I tried to dig into the extension to see if I could find something, but I'm just not familiar enough with it to know for sure.  I'd need to know a lot more about SVG files to figure out how it's actually looping.

**Comment by jondale** [comment]
Can you send me an example file where this is happening?

If you put everything into one layer does it then work as expected?

**Comment by laz1861** [comment]
This was the file that was doing it for me.  I was specifically trying to
cut out the piece with the three semicircles, so I had it selected, and not
actually cutting the whole thing.

It would end up cutting the outline, then the outline and a couple of
holes, then the outline, a couple of holes, then the rest the holes.  I may
have made some changes after this save that caused the third round of
cutting, but there should be at least two layers associated with that piece.

**Comment by jondale** [comment]
Did the image attach?  I can't seem to find it.

**Comment by laz1861** [comment]
So, we were able to confirm that this is related to layers on my computer.  I copied the paths to a new document and pasted them all into the same layer and it seemed to fix everything.  But Jondale was saying that he couldn't replicate this on his machine.  Has anyone else noticed problems with this?

**Comment by bmanifold** [comment]
Was anyone ever able to replicate this problem?

**Comment by laz1861** [comment]
I think I've got an idea on why this is happening.  I think it's related to the layer creation step in the tabbed box maker.  If you use the tabbed box maker more than once, you can end up with duplicate layers with the same name.  I need to see if I can nail down an exact use case to figure out why it's happening.

**Comment by jondale** [comment]
Creating multiple layers of the same paths is expected behavior when running the tabbed box extension multiple times.  The gcode is just being created for each layer.  Closing this issue.
